export const design = [
  {
    "type": "Classification",
    "col": 0,
    "row": 0,
    "designRow": 0,
    "width": 2,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_classification",
      "dss_attr_label": "Классификация",
      "dss_component_reference": "ddt_classification",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 0,
    "row": 1,
    "designRow": 2,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_status",
      "dss_attr_label": "Статус",
      "dss_component_reference": "ddt_document_status",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 1,
    "row": 1,
    "designRow": 2,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_stamp",
      "dss_attr_label": "Гриф",
      "dss_component_reference": "ddt_dict_stamp",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Text",
    "col": 0,
    "row": 2,
    "designRow": 4,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_reg_number",
      "dss_attr_label": "Регистрационный номер",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Date",
    "col": 1,
    "row": 2,
    "designRow": 4,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsdt_reg_date",
      "dss_attr_label": "Дата регистрации",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": true,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Text",
    "col": 0,
    "row": 3,
    "designRow": 6,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_work_number",
      "dss_attr_label": "Временный номер",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Date",
    "col": 1,
    "row": 3,
    "designRow": 6,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsdt_creation_date",
      "dss_attr_label": "Дата создания",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "TextArea",
    "col": 0,
    "row": 4,
    "designRow": 8,
    "width": 2,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_description",
      "dss_attr_label": "Краткое содержание",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 0,
    "row": 5,
    "designRow": 10,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_signer_empl",
      "dss_attr_label": "Подписант",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly_if_not:dss_reg_number,$dss_work_number",
      "dsb_multiply": true,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": "signature.restriction_selection",
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 1,
    "row": 5,
    "designRow": 10,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_vrio_empl",
      "dss_attr_label": "Подписант (ВРИО)",
      "dss_component_reference": null,
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 0,
    "row": 6,
    "designRow": 12,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_author_empl",
      "dss_attr_label": "Автор",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "TextArea",
    "col": 1,
    "row": 6,
    "designRow": 12,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_reason",
      "dss_attr_label": "Основание подготовки",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 0,
    "row": 7,
    "designRow": 14,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "restrict_document_participants",
      "dss_attr_label": "Получатели документа",
      "dss_component_reference": null,
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": true,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": "visible_in:dsid_stamp,[0000abcd0000682o, 0000000000000252]",
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": "Пожалуйста, укажите сотрудников с допуском к документу",
      "dsb_highlight_on_form": true,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Checkbox",
    "col": 1,
    "row": 7,
    "designRow": 14,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsb_important",
      "dss_attr_label": "Важный документ",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 0,
    "row": 8,
    "designRow": 16,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_control_v",
      "dss_attr_label": "Контроль",
      "dss_component_reference": "ddt_dict_control",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": "visible_if:dsid_control_v,0000vols00003ryg",
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 1,
    "row": 8,
    "designRow": 16,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_document_subtype",
      "dss_attr_label": "Подтип",
      "dss_component_reference": "ddt_dict_document_subtype",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly_if_not:dss_reg_number,$dss_work_number",
      "dsb_multiply": false,
      "dss_validation_rule": "required",
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 0,
    "row": 9,
    "designRow": 18,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_document_kind",
      "dss_attr_label": "Вид документа",
      "dss_component_reference": "ddt_dict_ord",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Text",
    "col": 1,
    "row": 9,
    "designRow": 18,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsi_number_of_appendix",
      "dss_attr_label": "Количество приложений",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Text",
    "col": 0,
    "row": 10,
    "designRow": 20,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsi_number_of_page",
      "dss_attr_label": "Количество листов",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Combobox",
    "col": 0,
    "row": 11,
    "designRow": 22,
    "width": 2,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_themes",
      "dss_attr_label": "Тематика",
      "dss_component_reference": "ddt_dict_themes",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly_if_not:dss_reg_number,$dss_work_number",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "TextArea",
    "col": 0,
    "row": 12,
    "designRow": 24,
    "width": 2,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_note",
      "dss_attr_label": "Отметки канцелярии",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "DocStatus",
    "col": 0,
    "row": 13,
    "designRow": 26,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dss_ord_status",
      "dss_attr_label": "Состояние",
      "dss_component_reference": "ddt_dict_doc_status",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "filters": [
        {
          "type": "depends_on",
          "field": "types",
          "filter": "docType"
        }
      ],
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "DocumentPicker",
    "col": 1,
    "row": 13,
    "designRow": 26,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_document_basis",
      "dss_attr_label": "Документ основание",
      "dss_component_reference": [
        "ddt_ord_type_doc"
      ],
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": "visible_if:dsid_doc_status,0000abcd000052vc",
      "dss_display_template": "${dss_reg_number} от ${dsdt_reg_date ? dsdt_reg_date: dsdt_creation_date}",
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Checkbox",
    "col": 0,
    "row": 14,
    "designRow": 28,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsb_hardcopy_sgn",
      "dss_attr_label": "Подписан на бланке",
      "dss_component_reference": "",
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 0,
    "row": 15,
    "designRow": 30,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_register_empl",
      "dss_attr_label": "Зарегистрировавшее лицо",
      "dss_component_reference": "",
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Orgstructure",
    "col": 1,
    "row": 15,
    "designRow": 30,
    "width": 1,
    "height": 1,
    "attr": {
      "dss_attr_name": "dsid_signature_performer_empl",
      "dss_attr_label": "Исполнитель задания подписания",
      "dss_component_reference": null,
      "dsb_readonly": false,
      "dss_readonly_rule": null,
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  },
  {
    "type": "Text",
    "col": 0,
    "row": 16,
    "designRow": 32,
    "width": 2,
    "height": 1,
    "attr": {
      "dss_attr_name": "i_global_id",
      "dss_attr_label": "Глобальный идентификатор",
      "dss_component_reference": null,
      "dsb_readonly": true,
      "dss_readonly_rule": "readonly",
      "dsb_multiply": false,
      "dss_validation_rule": null,
      "dss_validation_error": null,
      "dss_visible_rule": null,
      "dss_display_template": null,
      "dss_display_stamp": null,
      "dss_placeholder": null,
      "dsb_highlight_on_form": false,
      "query_parameters": null,
      "dss_stamp_visibility_rule": null,
      "dss_search_filter": null
    }
  }
]

export const docData = {
  "type": "ddt_ord_type_doc",
  "id": "77000014004cy9ig",
  "globalId": null,
  "values": {
    "dss_note": null,
    "dss_dir_surname": null,
    "dsdt_creation_date": "01.09.2022 23:10:51",
    "dsc_barcode": null,
    "dsid_stamp_pos": null,
    "dsid_organization": null,
    "dsid_reserv_number_pool": null,
    "dss_work_number": "ВР-19180-2",
    "dsid_themes": null,
    "dsid_control_v": null,
    "dsid_author_empl": "770000140005s7hh",
    "dsi_number_of_page": 0,
    "dss_status": "registered",
    "dsi_number_of_appendix": 0,
    "dsdt_reg_date": "01.09.2022 23:11:05",
    "dsid_policy": "770000140013o3z8",
    "dsc_rendition": null,
    "r_creation_date": "01.09.2022 23:10:51",
    "dsid_executor_empl": "770000140005s7hh",
    "dsid_classification": "77000014000xrymw",
    "dss_document_subtype": null,
    "dsb_to_sign": false,
    "dss_barcode": null,
    "dsid_document_kind": "0000000000000sKg",
    "r_object_id": "77000014004cy9ig",
    "r_creator_name": "User3",
    "dss_ord_status": "active",
    "dsid_document_subtype": "770000140011m01c",
    "drid_addressee_empl": null,
    "dsid_doc_status": null,
    "i_deleted": false,
    "dss_status_change_reason": "false",
    "i_global_id": "77000014004cy9ig",
    "dsb_important": false,
    "dsid_signer_empl": [
      "770000140005s7hh"
    ],
    "r_modifier_name": "master",
    "dsid_document_basis": null,
    "dss_doc_type": "ddt_ord_type_doc",
    "dss_reason": null,
    "dss_description": "ыыы",
    "dsid_register_empl": "770000140005s7hh",
    "dss_doc_status": "not_entered",
    "dss_signer_branch": [
      "Тестовый Филиал"
    ],
    "dss_reg_number": "777-ВЭ-2",
    "dsid_stamp": "000000000000023q",
    "dss_home": "LENENERGO",
    "dsb_deleted": false,
    "dss_content_name": null,
    "dss_sk_1c_guid": null,
    "r_modify_date": "01.09.2022 23:11:04",
    "dsb_hardcopy_sgn": false,
    "dss_signer_organization": [
      "ПАО \"ЛЕНЭНЕРГО\""
    ],
    "dsc_content": "77000014004cy9ik"
  },
  "valuesCustom": {
    "r_object_id": "77000014004cy9ig",
    "dss_ord_status": {
      "r_object_id": "77000014000c1m9u",
      "r_creator_name": "master",
      "dsb_unique_choice": false,
      "r_creation_date": "04.12.2019 13:47:18",
      "dss_name": "Действует",
      "dsb_inactive": false,
      "dsb_show_in_list": true,
      "dsb_display_on_form": false,
      "r_modifier_name": "master",
      "r_modify_date": "02.09.2022 09:48:21",
      "dsi_sort_order": 2,
      "dss_system_name": "active",
      "dsb_default": false
    },
    "dsid_document_subtype": {
      "r_object_id": "770000140011m01c",
      "dss_name": "Приказ"
    },
    "drid_addressee_empl": null,
    "dsdt_creation_date": "01.09.2022 23:10:51",
    "i_global_id": "77000014004cy9ig",
    "dsb_important": false,
    "dsid_signer_empl": [
      {
        "lastName": "Автотест2",
        "positionLevel": null,
        "avatartId": null,
        "positionLevelName": null,
        "userName": null,
        "branch": "Тестовый Филиал",
        "isFederated": null,
        "emplId": "770000140005s7hh",
        "firstName": null,
        "inactive": null,
        "phone": null,
        "organization": "ПАО \"ЛЕНЭНЕРГО\"",
        "middleName": null,
        "position": "Сотрудник",
        "department": "Департамент 2",
        "email": null
      }
    ],
    "dss_description": "ыыы",
    "dss_work_number": "ВР-19180-2",
    "dsid_author_empl": {
      "lastName": "Автотест2",
      "positionLevel": null,
      "avatartId": null,
      "positionLevelName": null,
      "userName": "User3",
      "branch": "Тестовый Филиал",
      "isFederated": null,
      "emplId": "770000140005s7hh",
      "firstName": null,
      "inactive": null,
      "phone": null,
      "organization": "ПАО \"ЛЕНЭНЕРГО\"",
      "middleName": null,
      "position": "Сотрудник",
      "department": "Департамент 2",
      "email": null
    },
    "dsi_number_of_page": 0,
    "dss_status": {
      "r_object_id": "registered",
      "dss_name": "Зарегистрирован",
      "dsb_archival": false
    },
    "dsi_number_of_appendix": 0,
    "dsdt_reg_date": "01.09.2022 23:11:05",
    "dsid_nomenclature": null,
    "dsid_register_empl": {
      "lastName": "Автотест2",
      "positionLevel": null,
      "avatartId": null,
      "positionLevelName": null,
      "userName": "User3",
      "branch": "Тестовый Филиал",
      "isFederated": null,
      "emplId": "770000140005s7hh",
      "firstName": null,
      "inactive": null,
      "phone": null,
      "organization": "ПАО \"ЛЕНЭНЕРГО\"",
      "middleName": null,
      "position": "Сотрудник",
      "department": "Департамент 2",
      "email": null
    },
    "dsid_executor_empl": {
      "lastName": "Автотест2",
      "positionLevel": null,
      "avatartId": null,
      "positionLevelName": null,
      "userName": "User3",
      "branch": "Тестовый Филиал",
      "isFederated": null,
      "emplId": "770000140005s7hh",
      "firstName": null,
      "inactive": null,
      "phone": null,
      "organization": "ПАО \"ЛЕНЭНЕРГО\"",
      "middleName": null,
      "position": "Сотрудник",
      "department": "Департамент 2",
      "email": null
    },
    "dss_doc_status": {
      "r_object_id": "77000014000c1m9t",
      "r_creator_name": "master",
      "dsb_unique_choice": false,
      "r_creation_date": "04.12.2019 13:47:18",
      "dss_name": "Не вступил в силу",
      "dsb_inactive": false,
      "dsb_show_in_list": true,
      "dsb_display_on_form": false,
      "r_modifier_name": "master",
      "r_modify_date": "02.09.2022 09:48:21",
      "dsi_sort_order": 1,
      "dss_system_name": "not_entered",
      "dsb_default": false
    },
    "dss_signer_branch": [
      "Тестовый Филиал"
    ],
    "dss_reg_number": "777-ВЭ-2",
    "dsid_classification": "Распорядительные документы / Приказ",
    "dsid_stamp": {
      "r_object_id": "000000000000023q",
      "dsb_encryption": false,
      "dss_name": "Общего пользования"
    },
    "dss_home": null,
    "dsb_hardcopy_sgn": false,
    "dsb_to_sign": false,
    "dss_signer_organization": [
      "ПАО \"ЛЕНЭНЕРГО\""
    ],
    "dsid_document_kind": {
      "r_object_id": "0000000000000sKg",
      "dss_name": "Приказ"
    },
    "dsc_content": {
      "dssEehdBarcode": null,
      "iGlobalId": "77000014004cy9ik",
      "dsidAuthorEmpl": "770000140005s7hh",
      "versionsCount": 1,
      "isSenbToEehd": false,
      "contentId": "77000014004csx88",
      "main": true,
      "contentName": "1.png",
      "dssAuthorName": "User3",
      "currentVersionLabel": "1.0",
      "dsdtCreationDate": "01.09.2022 23:10:51",
      "dsidContentType": "main_content",
      "dssAuthorDepartmentName": "Департамент 2",
      "dssAuthorFio": "Автотест2",
      "dssAuthorPositionName": "Сотрудник",
      "id": "77000014004cy9ik",
      "contentTypeName": "Основной контент"
    }
  },
  "state": {
    "dss_name": "Зарегистрирован",
    "r_object_id": "registered",
    "nameRu": "Зарегистрирован",
    "order": 6,
    "stopParameter": null
  },
  "docState": null,
  "documentActions": [
    {
      "caption": "Создать резолюцию",
      "name": "create_resolution",
      "permits": null,
      "dss_valid_condition": "",
      "dss_title_window": "",
      "dss_text_window": "",
      "signal": null,
      "autoClose": false,
      "signatureRequired": false,
      "parameters": null,
      "bpSettingKey": null
    },
    {
      "caption": "Сохранить",
      "name": "save",
      "permits": null,
      "dss_valid_condition": "",
      "dss_title_window": "",
      "dss_text_window": "",
      "signal": null,
      "autoClose": false,
      "signatureRequired": false,
      "parameters": null,
      "bpSettingKey": null
    },
    {
      "caption": "Удалить",
      "name": "delete",
      "permits": null,
      "dss_valid_condition": "",
      "dss_title_window": "",
      "dss_text_window": "",
      "signal": null,
      "autoClose": true,
      "signatureRequired": false,
      "parameters": null,
      "bpSettingKey": null
    },
    {
      "caption": "Выгрузить документ",
      "name": "export_doc",
      "permits": null,
      "dss_valid_condition": null,
      "dss_title_window": null,
      "dss_text_window": null,
      "signal": null,
      "autoClose": false,
      "signatureRequired": false,
      "parameters": null,
      "bpSettingKey": null
    },
    {
      "caption": "Печать карточки",
      "name": "print_card",
      "permits": [],
      "dss_valid_condition": null,
      "dss_title_window": null,
      "dss_text_window": null,
      "signal": null,
      "autoClose": false,
      "signatureRequired": false,
      "parameters": null,
      "bpSettingKey": null
    }
  ],
  "documentTabs": [
    {
      "name": "content",
      "caption": "Контент",
      "permits": [
        "manage_attachment_version"
      ],
      "settings": null,
      "parameters": null
    },
    {
      "name": "requisites",
      "caption": "Реквизиты",
      "permits": [
        "save",
        "change_doc_state",
        "work_ext_addressees"
      ],
      "settings": null,
      "parameters": {
        "signature": {
          "min_position_level": 4
        }
      }
    },
    {
      "name": "approval-sheet",
      "caption": "Согласование и подписание",
      "permits": [
        "delete"
      ],
      "settings": [
        "agreement",
        "show_auto_approve"
      ],
      "parameters": {
        "agreement": {},
        "signature": {
          "min_position_level": "4",
          "restriction_selection": "ord_signer"
        },
        "review": {
          "restriction_selection": "documentary_maintanance"
        }
      }
    },
    {
      "name": "links",
      "caption": "Связанные документы",
      "permits": [
        "link"
      ],
      "settings": null,
      "parameters": null
    },
    {
      "name": "comments",
      "caption": "Комментарии",
      "permits": [],
      "settings": null,
      "parameters": null
    },
    {
      "name": "resolutions",
      "caption": "Резолюции",
      "permits": [
        "save",
        "create_subresolution",
        "CREATE"
      ],
      "settings": null,
      "parameters": null
    },
    {
      "name": "familiarization",
      "caption": "Рассылка",
      "permits": [],
      "settings": null,
      "parameters": null
    },
    {
      "name": "audit",
      "caption": "История",
      "permits": [],
      "settings": null,
      "parameters": null
    },
    {
      "name": "handouts",
      "caption": "Выданные на руки",
      "permits": [],
      "settings": null,
      "parameters": null
    }
  ],
  "tags": [],
  "highlights": null,
  "performers": null,
  "attachments": [],
  "useContentTemplate": null,
  "isFederative": false,
  "contentRequired": true,
  "deletable": false,
  "useForScanning": false,
  "waitMimeTypePintCard": "docx",
  "classificationId": "77000014000xrymw",
  "approverId": null,
  "display": null,
  "documentColorCss": null,
  "isFederativeType": true,
  "existsInFolders": false,
  "noUnusedQuestions": false,
  "dsidSign": null,
  "externalCorrespondent": null,
  "overdueResolutionExists": false,
  "lessThan5DaysOverdueResolutionExists": false,
  "lessThan10DaysOverdueResolutionExists": false,
  "overdueResolutionNotExists": false,
  "showOverdueState": false,
  "batchMailId": null,
  "dzkParticipantRoles": []
}