export const LOGIN_PAGE_PATH = '/login'
export const RESET_PASSWORD_PAGE_PATH = '/reset_password'
export const TASK_LIST_PATH = '/task'
export const MAIN_PATH = '/'
export const TASK_ITEM_PATH = '/task/:id/*'
export const VOLUME_ITEM_PATH = '/volume/:id'
